#+TITLE: Regulamento Roma II: a lei aplicável à responsabilidade extracontratual do produtor
#+AUTHOR: João Gomes de Almeida

* Introdução e delimitação do tema do estudo

A sociedade moderna é uma sociedade global. Os processos de conceção, produção, distribuição, comercialização e aquisição de produtos não se encontram, necessariamente, confinados ao território de um Estado. Todos nós adquirimos e utilizamos produtos que foram concebidos e produzidos em Estados diferentes daquele em que o adquirimos. Os meios de comunicação à distância, em particular a /Internet/, facilitam a aquisição de produtos comercializados em Estados diferentes do da residência habitual do adquirente. A sociedade moderna pauta-se também por uma facilidade (mitigada nos últimos anos pela pandemia que vivemos) sem precedentes de deslocação de pessoas além fronteiras. Não é, por isso, invulgar que um produto seja adquirido num Estado e deslocado para outro.

Assim, os casos de responsabilidade do produtor por danos causados por um produto têm, muitas vezes, pontos de contacto relevantes com mais de um Estado e suscitam os problemas específicos de determinação do tribunal internacionalmente competente, da lei aplicável e do reconhecimento de decisões estrangeiras. O presente estudo foca-se determinação da lei aplicável, em concreto na determinação da lei reguladora da obrigação extracontratual do produtor, adotando a perspetiva da ordem jurídica portuguesa.

Inicia-se com um breve contexto histórico, onde se dará conta, em traços gerais, da solução que vigorou na ordem jurídica portuguesa e do processo legislativo do Regulamento Roma II[fn:2], onde se encontram hoje consagradas as normas de conflitos que determinam a lei aplicável à responsabilidade extracontratual do produtor por danos causados por produtos. De seguida, atende-se aos valores prosseguidos e, em traços gerais, às conexões adotadas, procurando dar-se uma panorâmica de como elas se coordenam. Procede-se, depois, a análise de cada uma dessas conexões, após o que se apresentam as nossas conclusões.

* Breve contexto histórico

Antes do Regulamento Roma II, a Conferência da Haia aprovou a Convenção da Haia de 1973 sobre a Lei Aplicável à Responsabilidade Decorrente de Produtos. Esta Convenção entrou internacionalmente em vigor em 1 de outubro de 1977, mas não pode considerar-se um sucesso, uma vez que, em outubro de 2021, é aplicável apenas em 8 Estados Contratantes[fn:1]. A razão para um tão escasso número de Estados Contratantes parece encontrar-se na elevada complexidade da solução conflitual que adotou[Cf., por exemplo, @graziano2005, p. 480; @pinheiro2015, p. 489; contra, considerando duvidoso que uma regra simples consiga atender aos interesses envolvidos nesta matéria, cf. @fawcett1993, pp. 154-155]. Segundo a Convenção, a lei reguladora da responsabilidade decorrente de produtos é: /(i)/ a lei do Estado da residência habitual do lesado se esse Estado for também o do estabelecimento principal do alegado agente /ou/ o do lugar onde o produto foi adquirido pelo lesado (artigo 5.º); na falta desta, /(ii)/ a lei do Estado do lugar onde ocorreu o dano direto se esse Estado for também o da residência habitual do lesado, o do estabelecimento principal do alegado agente /ou/ o do lugar onde o produto foi adquirido pelo lesado (artigo 4.º); na falta desta, /(iii)/ a lei do Estado estabelecimento principal do alegado agente ou do lugar onde ocorreu o dano direto, consoante a escolha do lesado (artigo 6.º); contudo, /(iv)/ será aplicável a lei do Estado do estabelecimento principal do alegado agente se este demonstrar que não podia razoavelmente prever que o produto ou os seus produtos do mesmo tipo seriam disponibilizados nos Estados da residência habitual do lesado ou do lugar onde ocorreu o dano direto (artigo 7.º)[Cf. @reese1973, pp. 263-264.].

Portugal iniciou, mas não concluiu, o processo de vinculação a esta Convenção. O Direito de Conflitos português de fonte interna não contém uma norma de conflitos especial em matéria de responsabilidade do produtor decorrente de danos causados por produtos. A lei aplicável à responsabilidade do produtor, quando revista natureza extracontratual, é determinada de acordo com as normas de conflitos gerais em matéria de responsabilidade extracontratual, previstas no artigo 45.º do Código Civil[Cf., sobre este preceito, @machado1995, pp. 367-377; @vicente2001, pp. *XX*; @pissarra2004, pp. 107 e ss.; @pires2009, pp. 113-117; @oliveira2011, pp. *XX*; @fernandes2014, pp. 123-128; @pinheiro2015, pp. 500-501; @vicente2020, pp. 200-204.].

No artigo 45.º, n.º 1, do Código Civil consagrou-se a regra clássica em matéria de responsabilidade extracontratual: é aplicável a /lex loci delicti comissi/, i.é., a lei do Estado onde decorreu a principal atividade causadora do prejuízo ou, no caso da responsabilidade por omissão, a lei do Estado onde o responsável deveria ter agido. No caso da responsabilidade do produtor, nem sempre será fácil determinar onde decorreu a principal atividade causadora do prejuízo. Em muitos casos, o lugar onde foi fabricado o produto será aquele em que decorreu a principal atividade causadora do prejuízo[Cf., neste sentido, @silva1990, p. 142.]. Contudo, nos casos em que o produto é desenhado num Estado, produzido noutro e colocado no comércio num terceiro, parece que a resposta deve variar em função da natureza do defeito[@fawcett1993, 211.].

O artigo 45.º, n.º 2, dá relevância à /lex laesi/, i. é, à lei do lugar do efeito lesivo desde que /(i)/ esta considere o agente responsável, ao contrário da /lex loci delicti comissi/; e /(ii)/ fosse previsível para o agente a produção de um dano no Estado da lei do efeito lesivo. Os casos de responsabilidade do produtor são terreno fertil para se verificar uma dissociação entre o lugar da prática do facto e o lugar do efeito lesivo: é comum que um (determinado tipo de) produto seja comercializado em vários Estados (sendo ou não um deles o Estado em que foi produzido). Se o produto foi adquirido num Estado que não é o aquele em que foi produzido da produção e aí causou um dano, teremos, em regra, uma dissociação entre o lugar da principal atividade causadora do prejuízo (Estado em que o produto foi produzido) e o lugar em que ocorreu a lesão do bem jurídico (Estado em que o produto foi adquirido). A primeira das duas condições previstas no artigo 45.º, n.º 2, do Código Civil é controvertida: alguns autores advogam que a /lex laesi/ se deve aplicar, quando seja mais favorável para o lesado, mesmo que a /lex loci delicti comissi/ considere o agente responsável[Cf.  @vicente2001, p. 489; e, aderindo a esta posição, @pissarra2004, 163.]; outros sustentam, numa interpretação mais próxima da letra do preceito, que só é possível aplicar a /lex laesi/ quando a /lex loci delicti comissi/ não considere o agente responsável[Cf. @machado1995, p. 371; @fernandes2014, *XX*; e @pinheiro2015, p. 501. Na jurisprudência acompanharam esta posição o Supremo Tribunal de Justiça, nos seus acórdãos de 11 de abril de 2013, proc. 186/10.6TBCBT.S2, e de 14 de janeiro de 2014, proc. 1032/08.6TBMTA.L1.S1, o Tribunal da Relação de Guimarães, no acórdão de 29 de outubro de 2013, proc. 225/12.6TBAMR.G1, e o Tribunal da Relação do Porto, no acórdão de 9 de maio de 2013, proc. 1782/06.2TBAMT.P1.].

O artigo 45.º, n.º 3, consagra novo desvio à /lex loci delicti comissi/: se agente e lesado tiverem nacionalidade ou residência habitual comum, e se encontrarem ocasionalmente em país estrangeiro, é aplicável a lei da nacionalidade ou residência habitual comum, sem prejuízo da aplicação das normas do Estado local que devem ser aplicáveis indistintamente a todas as pessoas. A aplicação desta regra aos casos de responsabilidade do produtor suscita dúvidas. Atualmente, os produtores são, em regra, pessoas coletivas. As pessoas coletivas não têm nacionalidade ou residência habitual. Pode e deve equivaler-se a sede à nacionalidade ou residência habitual da pessoa singular. Ainda assim, dificilmente se encontrará preenchido o requisito de agente e lesado se encontrarem /ocasionalmente/ em país estrangeiro. Não será ocasional a "presença" do produtor nos países em que o seu produto é colocado em circulação[fn:3].

O processo legislativo do Regulamento Roma II iniciou-se com a apresentação, em 22 de julho de 2003, pela Comissão Europeia, da sua proposta de Regulamento do Parlamento Europeu e do Conselho sobre a Lei Aplicável às Obrigações Extracontratuais ("Roma II")[fn:4]. Nesta proposta, a lei aplicável à responsabilidade decorrente de produtos é determinada, em primeiro lugar, pela /professio iuris/ (artigo 10.º da Proposta). Nos casos em que agente e lesado não escolham a lei aplicável, será aplicável a lei do Estado da residência habitual comum; na falta desta, é aplicável a lei do Estado da residência habitual do lesado, desde que o produto[fn:5] seja aí comercializado com o consentimento da pessoa cuja responsabilidade é invocada; caso tal não suceda, é aplicável a lei do Estado da residência habitual da pessoa cuja responsabilidade é invocada. A aplicação da lei do Estado da residência habitual comum, da residência habitual do lesado e da residência habitual da pessoa cuja responsabilidade é invocada deve ser afastada em favor da lei de um outro Estado que, no caso concreto, apresente uma conexão manifestamente mais estreita (artigo 4.º da Proposta[fn:7]).

Em suma, a Comissão Europeia defendeu, na sua Proposta, a consagração de uma norma de conflitos especial em matéria de lei aplicável à responsabilidade decorrente de produtos. No essencial, a norma de conflitos proposta limita-se à substituição da /lex damni/ (artigo 3.º, n.º 1, da Proposta) pela lei do Estado da residência habitual do lesado ou do agente. É interessante verificar que a Comissão Europeia ponderou a solução da Convenção da Haia e considerou que a solução conflitual a adotar "não deve ser desnecessariamente complexa"[fn:6].

O Parlamento Europeu, em primeira leitura[fn:8], recomendou a eliminação da norma conflitos especial sobre responsabilidade decorrente de produtos. A lei aplicável seria assim determinada pelas normas de conflitos gerais. O Parlamento Europeu recomendou igualmente o aditamento de vários critérios à cláusula de exceção, bastante vagos e aparentemente inspirados no /Restatement (Second) of the Conflict of Laws/ do /American Law Institute/[Cf., neste sentido,  @illmer2009, p. 277; @illmer2011, 115.].





* Conexão primária: autonomia privada
* Conexão subsidiária
** Residência habitual comum (art. 4.º/2)
** Conexões cumulativas sucessivas ou subsidárias (art. 5.º/1)
** A cláusula de exceção (art. 5.º/2)
* A relevância de normas de aplicação imediata (art. 16.º)
* Conclusões

* Footnotes
[fn:8] P6_TA(2005)0284.

[fn:7] O artigo 4.º da Proposta estabelecia: "Sem prejuízo do disposto nos nºs 2 e 3 do artigo 3º, a lei aplicável à obrigação extracontratual em caso de dano ou risco de dano causado por um produto defeituoso é a lei do país em que a pessoa lesada tem a sua residência habitual, salvo se a pessoa cuja responsabilidade é invocada provar que o produto foi comercializado neste país sem o seu consentimento, sendo então aplicável a lei do país em que a pessoa cuja responsabilidade é invocada tem a sua residência habitual."

[fn:6] Cf. exposição de motivos da Proposta, p. 15.

[fn:5] O concreto produto que causou o dano ou um produto do mesmo tipo. Isso decorre claramente da exposição de motivos da Proposta: "Quando a pessoa lesada adquire o produto num país diferente do da sua residência habitual, por exemplo, durante uma viagem, devem distinguir-se duas hipóteses: na primeira, adquiriu no estrangeiro um produto que é igualmente comercializado no país da sua residência, por exemplo, para beneficiar de uma promoção. Neste caso, o produtor já tinha previsto que a sua
actividade poderia ser avaliada ao abrigo das normas em vigor neste país e o artigo 4º designa a lei deste país cuja aplicação era previsível para as duas partes." (cf. p. 15).

[fn:4] COM(2003) 427 final. Doravante Proposta.

[fn:3] O Supremo Tribunal de Justiça caracterizou como ocasional "a estadia sem grande estabilidade e permanência, antes a título transitório e passageiro, ou seja, para durar por um período limitado, circunscrita à realização de um fim ou atividade pouco prolongada." (acórdão de 8 de novembro de 1979, /Boletim do Ministério da Justiça/, n.º 291, pp. 456 e ss.).

[fn:2] Regulamento (CE) n.º 864/2007 do Parlamento Europeu e do Conselho, de 11 de Julho de 2007, relativo à lei aplicável às obrigações extracontratuais (Roma II), publicado no Jornal Oficial L 199, de 31 de julho de 2007.

[fn:1] A saber, Croácia, Eslóvenia, Espanha, Finlândia, França, Macedónia do Norte, Montenegro, Países Baixos e Sérvia.
