#+TITLE: Regulamento Roma II: a lei aplicável à responsabilidade extracontratual do produtor
#+AUTHOR: João Gomes de Almeida

* Introdução e delimitação do tema do estudo

A sociedade moderna é uma sociedade global. Os processos de conceção, produção, distribuição, comercialização e aquisição de produtos não se encontram, necessariamente, confinados ao território de um Estado. Todos nós adquirimos e utilizamos produtos que foram concebidos e produzidos em Estados diferentes daquele em que o adquirimos. Os meios de comunicação à distância, em particular a /Internet/, facilitam a aquisição de produtos comercializados em Estados diferentes do da residência habitual do adquirente. A sociedade moderna pauta-se também por uma facilidade (mitigada nos últimos anos pela pandemia que vivemos) sem precedentes de deslocação de pessoas além fronteiras. Não é, por isso, invulgar que um produto seja adquirido num Estado e deslocado para outro.

Assim, os casos de responsabilidade do produtor por danos causados por um produto têm, muitas vezes, pontos de contacto relevantes com mais de um Estado e suscitam os problemas específicos de determinação do tribunal internacionalmente competente, da lei aplicável e do reconhecimento de decisões estrangeiras. O presente estudo foca-se determinação da lei aplicável, em concreto na determinação da lei reguladora da obrigação extracontratual do produtor, adotando a perspetiva da ordem jurídica portuguesa.

Inicia-se com um breve contexto histórico, onde se dará conta, em traços gerais, da solução que vigorou na ordem jurídica portuguesa e do processo legislativo do Regulamento Roma II, onde se encontram hoje consagradas as normas de conflitos que determinam a lei aplicável à responsabilidade extracontratual do produtor por danos causados por produtos. De seguida, atende-se aos valores prosseguidos e, em traços gerais, às conexões adotadas, procurando dar-se uma panorâmica de como elas se coordenam. Procede-se, depois, a análise de cada uma dessas conexões, após o que se apresentam as nossas conclusões.

* Breve contexto histórico (a situação antes do Roma II e o processo legislativo)

Antes do Regulamento Roma II, a Conferência da Haia aprovou a Convenção da Haia de 1973 sobre a Lei Aplicável à Responsabilidade Decorrente de Produtos. Esta Convenção entrou internacionalmente em vigor em 1 de outubro de 1977, mas não pode considerar-se um sucesso, uma vez que, em outubro de 2021, é aplicável apenas em 8 Estados Contratantes[fn:1]. A razão para um tão escasso número de Estados Contratantes parece encontrar-se na elevada complexidade da solução conflitual que adotou[Cf., por exemplo, @graziano2005, p. 480; @pinheiro2015, p. 489; contra, considerando duvidoso que uma regra simples consiga atender aos interesses envolvidos nesta matéria, @fawcett1993, pp. 154-155]. Segundo a Convenção, a lei reguladora da responsabilidade decorrente de produtos é: /(i)/ a lei do Estado da residência habitual do lesado se esse Estado for também o do estabelecimento principal do alegado agente /ou/ o o do lugar onde o produto foi adquirido pelo lesado (artigo 5.º); na falta desta, /(ii)/ a lei do Estado do lugar onde ocorreu o dano direto se esse Estado for também o da residência habitual do lesado, o do estabelecimento principal do alegado agente /ou/ o o do lugar onde o produto foi adquirido pelo lesado (artigo 4.º); na falta desta, /(iii)/ a lei do Estado estabelecimento principal do alegado agente ou do lugar onde ocorreu o dano direto, consoante a escolha do lesado (artigo 6.º); contudo, /(iv)/ será aplicável a lei do Estado do estabelecimento principal do alegado agente se este demonstrar que não podia razoavelmente prever que o produto ou os seus produtos do mesmo tipo seriam disponibilizados nos Estados da residência habitual do lesado ou do lugar onde ocorreu o dano direto.

* Conexão primária: autonomia privada
* Conexão subsidiária
** Residência habitual comum (art. 4.º/2)
** Conexões cumulativas sucessivas ou subsidárias (art. 5.º/1)
** A cláusula de exceção (art. 5.º/2)
* A relevância de normas de aplicação imediata (art. 16.º)
* Conclusões

* Footnotes

[fn:1] A saber, Croácia, Eslóvenia, Espanha, Finlândia, França, Macedónia do Norte, Montenegro, Países Baixos e Sérvia.
