#+TITLE: Regulamento Roma II: a lei aplicável à responsabilidade extracontratual do produtor
#+AUTHOR: João Gomes de Almeida

* Introdução e delimitação do tema do estudo

A sociedade moderna é uma sociedade global. Os processos de conceção, produção, distribuição, comercialização e aquisição de produtos não se encontram, necessariamente, confinados ao território de um Estado. Todos nós adquirimos e utilizamos produtos que foram concebidos e produzidos em Estados diferentes daquele em que o adquirimos. Os meios de comunicação à distância, em particular a /Internet/, facilitam a aquisição de produtos comercializados em Estados diferentes do da residência habitual do adquirente. A sociedade moderna pauta-se também por uma facilidade (mitigada nos últimos anos pela pandemia que vivemos) sem precedentes de deslocação de pessoas além fronteiras. Não é, por isso, invulgar que um produto seja adquirido num Estado e deslocado para outro.

Assim, os casos de responsabilidade do produtor por danos causados por um produto têm, muitas vezes, pontos de contacto relevantes com mais de um Estado e suscitam os problemas específicos de determinação do tribunal internacionalmente competente, da lei aplicável e do reconhecimento de decisões estrangeiras. O presente estudo foca-se determinação da lei aplicável, em concreto na determinação da lei reguladora da obrigação extracontratual do produtor, adotando a perspetiva da ordem jurídica portuguesa.

Inicia-se com um breve contexto histórico, onde se dará conta, em traços gerais, da solução que vigorou na ordem jurídica portuguesa e do processo legislativo do Regulamento Roma II[fn:2], onde se encontram hoje consagradas as normas de conflitos que determinam a lei aplicável à responsabilidade extracontratual do produtor por danos causados por produtos. De seguida, atende-se aos objetivos prosseguidos e, em traços gerais, às conexões adotadas, procurando dar-se uma panorâmica de como elas se coordenam. Procede-se, depois, a análise de cada uma dessas conexões, após o que se apresentam as nossas conclusões.

* Breve contexto histórico

Antes do Regulamento Roma II, a Conferência da Haia aprovou a Convenção da Haia de 1973 sobre a Lei Aplicável à Responsabilidade Decorrente de Produtos[fn:17]. Esta Convenção entrou internacionalmente em vigor em 1 de outubro de 1977, mas não pode considerar-se um sucesso, uma vez que, em outubro de 2021, é aplicável apenas em 8 Estados Contratantes[fn:1]. A razão para um tão escasso número de Estados Contratantes parece encontrar-se na elevada complexidade da solução conflitual que adotou[Cf., por exemplo, @graziano2005, p. 480; @pinheiro2015, p. 489; contra, considerando duvidoso que uma regra simples consiga atender aos interesses envolvidos nesta matéria, cf. @fawcett1993, pp. 154-155]. Segundo a Convenção, a lei reguladora da responsabilidade decorrente de produtos é: /(i)/ a lei do Estado da residência habitual do lesado se esse Estado for também o do estabelecimento principal do alegado agente /ou/ o do lugar onde o produto foi adquirido pelo lesado (artigo 5.º); na falta desta, /(ii)/ a lei do Estado do lugar onde ocorreu o dano direto se esse Estado for também o da residência habitual do lesado, o do estabelecimento principal do alegado agente /ou/ o do lugar onde o produto foi adquirido pelo lesado (artigo 4.º); na falta desta, /(iii)/ a lei do Estado estabelecimento principal do alegado agente ou do lugar onde ocorreu o dano direto, consoante a escolha do lesado (artigo 6.º); contudo, /(iv)/ será aplicável a lei do Estado do estabelecimento principal do alegado agente se este demonstrar que não podia razoavelmente prever que o produto ou os seus produtos do mesmo tipo seriam disponibilizados nos Estados da residência habitual do lesado ou do lugar onde ocorreu o dano direto (artigo 7.º)[Cf. @reese1973, pp. 263-264.].

Portugal iniciou, mas não concluiu, o processo de vinculação a esta Convenção. O Direito de Conflitos português de fonte interna não contém uma norma de conflitos especial em matéria de responsabilidade do produtor decorrente de danos causados por produtos. A lei aplicável à responsabilidade do produtor, quando revista natureza extracontratual, é determinada de acordo com as normas de conflitos gerais em matéria de responsabilidade extracontratual, previstas no artigo 45.º do Código Civil[Cf., sobre este preceito, @machado1995, pp. 367-377; @vicente2001, pp. *XX*; @pissarra2004, pp. 107 e ss.; @pires2009, pp. 113-117; @oliveira2011, pp. 350 e ss.; @fernandes2014c, pp. 123-128; @pinheiro2015, pp. 500-501; @brito2019, pp. 74-75; @vicente2020, pp. 200-204.].

No artigo 45.º, n.º 1, do Código Civil consagrou-se a regra clássica em matéria de responsabilidade extracontratual: é aplicável a /lex loci delicti comissi/, i.é., a lei do Estado onde decorreu a principal atividade causadora do prejuízo ou, no caso da responsabilidade por omissão, a lei do Estado onde o responsável deveria ter agido. No caso da responsabilidade do produtor, nem sempre será fácil determinar onde decorreu a principal atividade causadora do prejuízo. Em muitos casos, o lugar onde foi fabricado o produto será aquele em que decorreu a principal atividade causadora do prejuízo[Cf., neste sentido, @silva1990, p. 142.]. Contudo, nos casos em que o produto é desenhado num Estado, produzido noutro e colocado no comércio num terceiro, parece que a resposta deve variar em função da natureza do defeito[@fawcett1993, p. 211.].

O artigo 45.º, n.º 2, dá relevância à /lex laesi/, i. é, à lei do lugar do efeito lesivo desde que /(i)/ esta considere o agente responsável, ao contrário da /lex loci delicti comissi/; e /(ii)/ fosse previsível para o agente a produção de um dano no Estado da lei do efeito lesivo. Os casos de responsabilidade do produtor são terreno fertil para se verificar uma dissociação entre o lugar da prática do facto e o lugar do efeito lesivo: é comum que um (determinado tipo de) produto seja comercializado em vários Estados (sendo ou não um deles o Estado em que foi produzido). Se o produto foi adquirido num Estado que não é o aquele em que foi produzido e aí causou um dano, teremos, em regra, uma dissociação entre o lugar da principal atividade causadora do prejuízo (Estado em que o produto foi produzido) e o lugar em que ocorreu a lesão do bem jurídico (Estado em que o produto foi adquirido). A primeira das duas condições previstas no artigo 45.º, n.º 2, do Código Civil é controvertida: alguns autores advogam que a /lex laesi/ se deve aplicar, quando seja mais favorável para o lesado, mesmo que a /lex loci delicti comissi/ considere o agente responsável[Cf.  @vicente2001, p. 489; e, aderindo a esta posição, @pissarra2004, 163.]; outros sustentam, numa interpretação mais próxima da letra do preceito, que só é possível aplicar a /lex laesi/ quando a /lex loci delicti comissi/ não considere o agente responsável[Cf. @machado1995, p. 371; @fernandes2014c, 126; e @pinheiro2015, p. 501. Na jurisprudência acompanharam esta posição o Supremo Tribunal de Justiça, nos seus acórdãos de 11 de abril de 2013, proc. 186/10.6TBCBT.S2, e de 14 de janeiro de 2014, proc. 1032/08.6TBMTA.L1.S1, o Tribunal da Relação de Guimarães, no acórdão de 29 de outubro de 2013, proc. 225/12.6TBAMR.G1, e o Tribunal da Relação do Porto, no acórdão de 9 de maio de 2013, proc. 1782/06.2TBAMT.P1.].

O artigo 45.º, n.º 3, consagra novo desvio à /lex loci delicti comissi/: se agente e lesado tiverem nacionalidade ou residência habitual comum, e se encontrarem ocasionalmente em país estrangeiro, é aplicável a lei da nacionalidade ou residência habitual comum, sem prejuízo da aplicação das normas do Estado local que devem ser aplicáveis indistintamente a todas as pessoas. A aplicação desta regra aos casos de responsabilidade do produtor suscita dúvidas. Atualmente, os produtores são, em regra, pessoas coletivas. As pessoas coletivas não têm nacionalidade ou residência habitual. Pode e deve equivaler-se a sede à nacionalidade ou residência habitual da pessoa singular. Ainda assim, dificilmente se encontrará preenchido o requisito de agente e lesado se encontrarem /ocasionalmente/ em país estrangeiro. Não será ocasional, pelo menos em regra, a "presença" do produtor nos países em que o seu produto é colocado em circulação[fn:3].

O processo legislativo do Regulamento Roma II iniciou-se com a apresentação, em 22 de julho de 2003, pela Comissão Europeia, da sua proposta de Regulamento do Parlamento Europeu e do Conselho sobre a Lei Aplicável às Obrigações Extracontratuais ("Roma II")[fn:4]. Nesta proposta, a lei aplicável à responsabilidade decorrente de produtos é determinada, em primeiro lugar, pela /professio iuris/ (artigo 10.º da Proposta). Nos casos em que agente e lesado não escolham a lei aplicável, será aplicável a lei do Estado da residência habitual comum; na falta desta, é aplicável a lei do Estado da residência habitual do lesado, desde que o produto[fn:5] seja aí comercializado com o consentimento da pessoa cuja responsabilidade é invocada; caso tal não suceda, é aplicável a lei do Estado da residência habitual da pessoa cuja responsabilidade é invocada. A aplicação da lei do Estado da residência habitual comum, da residência habitual do lesado e da residência habitual da pessoa cuja responsabilidade é invocada deve ser afastada em favor da lei de um outro Estado que, no caso concreto, apresente uma conexão manifestamente mais estreita (artigo 4.º da Proposta[fn:7]).

Em suma, a Comissão Europeia defendeu, na sua Proposta, a consagração de uma norma de conflitos especial em matéria de lei aplicável à responsabilidade decorrente de produtos. No essencial, a norma de conflitos proposta limita-se à substituição da /lex damni/ (artigo 3.º, n.º 1, da Proposta) pela lei do Estado da residência habitual do lesado ou do agente. É interessante verificar que a Comissão Europeia ponderou a solução da Convenção da Haia e considerou que a solução conflitual a adotar "não deve ser desnecessariamente complexa"[fn:6].

O Parlamento Europeu, em primeira leitura[fn:8], recomendou a eliminação da norma conflitos especial sobre responsabilidade decorrente de produtos. A lei aplicável seria assim determinada pelas normas de conflitos gerais. O Parlamento Europeu recomendou igualmente o aditamento de vários critérios à cláusula de exceção, bastante vagos e aparentemente inspirados no /Restatement (Second) of the Conflict of Laws/ do /American Law Institute/[Cf., neste sentido,  @illmer2009, p. 277; @illmer2011, 115.].

A Comissão Europeia, em 21 de fevereiro de 2006, apresentou a sua Proposta alterada de Regulamento do Parlamento Europeu e do Conselho sobre a Lei Aplicável às Obrigações Extracontratuais ("Roma II")[fn:9]. Na sua Proposta alterada, a Comissão Europeia esclarece que não aceita as recomendações do Parlamento Europeu relativas à eliminação da norma de conflitos em matéria de responsabilidade decorrente de produtos e à redação da cláusula de exceção. Quanto a esta última, considera que a recomendação "traduzir-se-ia numa alteração substancial do espírito do instrumento" e que a redação proposta "pode transmitir uma mensagem que contraria o objetivo de previsibilidade prosseguido pelo regulamento"[fn:10]. A Comissão Europeia recusa a eliminação da norma de conflitos especial em matéria de responsabilidade decorrente de produtos por entender que a regra geral (/lex damni/) não permite prever a lei aplicável com razoável certeza, sendo, muitas vezes, fortuito o local do dano[fn:11]. A Comissão Europeia mantém a sua proposta de norma de conflitos especial em matéria de responsabilidade decorrente de produtos, com pequenos ajustes de redação[fn:12].

O Conselho, em 25 de setembro de 2006, adotou uma posição comum[fn:13]. O Conselho rejeitou a eliminação da norma de conflitos especial em matéria de responsabilidade decorrente de produtos, considerando que "a aplicação de regras gerais nos casos de responsabilidade por produtos defeituosos não permite prever a lei aplicável com uma certeza razoável", e a alteração proposta à cláusula de exceção por considerar "desnecessário fazer uma lista de factores específicos"[fn:14]. O Conselho rejeitou igualmente a solução conflitual proposta pela Comissão Europeia. Manteve a norma de conflitos especial, que atende à lei da residência habitual comum de agente e lesado e à cláusula de exceção, mas consagrou "um sistema em cascata de factores de conexão, associado a uma cláusula de previsibilidade"[fn:15].

Na sequência da Posição Comum, a Comissão Europeia proferiu uma comunicação na qual referiu que a proposta do Conselho em matéria de responsabilidade decorrente de produtos constitui "um desvio significativo quanto à abordagem adoptada em matéria de formulação, mas não em termos de intenção", que lamenta a adoção de um "sistema bastante complexo de aplicação «em cascata» de factores interrelacionados" e que "Continua convicta que a sua solução inicial assegurava uma solução igualmente equilibrada para os interesses em jogo, formulada de modo muito mais simples"[fn:16].

Nos momentos subsequentes do processo legislativo até à adoção e publicação do Regulamento Roma II, a norma de conflitos especial em matéria de responsabilidade decorrente de produtos não foi objeto de ulterior debate, tendo o Parlamento Europeu aceitado a redação dada pelo Conselho. Deste breve excurso pelo processo legislativo do Regulamento Roma II, verificamos que a opção por uma norma de conflitos especial nesta matéria não foi pacífica e que prevaleceu uma redação mais próxima da consagrada na Convenção da Haia, que tem sido criticado pela sua complexidade.

* Objetivos e panorâmica geral da solução conflitual adotada no Regulamento Roma II

No que respeita aos objetivos, podemos distinguir entre objetivos gerais do Regulamento Roma II e objetivos específicos em matéria de responsabilidade decorrente de produtos. Em geral, o Regulamento Roma II visa uniformizar as normas de conflitos em matéria de obrigações extracontratuais. Prossegue objetivos de certeza jurídica quanto à lei aplicável e de promoção da previsibilidade do resultado dos litígios[fn:18]. As normas de conflitos uniformes devem ser essencialmente formais, i.é., devem designar o Direito material aplicável sem atender ao conteúdo deste, com vista a evitar o risco de distorções da concorrência entre litigantes da União Europeia[fn:19], e assegurar um equilíbrio razoável entre os interesses da pessoa alegadamente responsável e os interesses do lesado[fn:20]. Nas palavras do Tribunal de Justica, são finalidades do Regulamento Roma II "garantir a previsibilidade das decisões dos litígios, a segurança jurídica quanto à lei aplicável e a aplicação uniforme do referido regulamento em todos os Estados-Membros"[fn:21].

O objetivo da justa ponderação de interesses é acentuado como objetivo específico em matéria de responsabilidade decorrente de produtos:

#+begin_quote
A regra de conflito de leis em matéria de responsabilidade por produtos defeituosos deverá responder aos objectivos que consistem na *justa repartição* dos riscos inerentes a uma sociedade moderna de alta tecnologia, na protecção da saúde dos consumidores, na promoção da inovação, na garantia de uma concorrência não falseada e na facilitação das trocas comerciais. A criação de um sistema em cascata de factores de conexão, acompanhada de uma cláusula de previsibilidade, constitui uma solução equilibrada em relação a estes objectivos. O primeiro aspecto a ter em conta é a lei do país onde o lesado tenha a sua residência habitual, no momento em que tenha ocorrido o dano, se o produto tiver sido comercializado nesse país. Os outros elementos da cascata são desencadeados se o produto não tiver sido comercializado nesse país, sem prejuízo do n.º 2 do artigo 4.º e da possibilidade de uma conexão manifestamente mais estreita com outro país[fn:22].
#+end_quote

No essencial, a norma de conflitos especial em matéria de responsabilidade decorrente de produtos visa designar uma lei que constitua um justo equilíbrio entre os interesses do lesado e do agente[fn:23], e assim acautelar objetivos mais gerais da União Europeia, como a saúde dos consumidores, a promoção da inovação e a salvaguarda da concorrência[Cf., neste sentido, @illmer2009, p. 281; @illmer2011, p. 116; @pinheiro2015, p. 488; @magnus2019, p. 214; @risso2019, p. 215 e ss..].

A solução conflitual em matéria de responsabilidade decorrente de produtos consagrada no Regulamento Roma II adota, como conexão primária, a escolha de lei pelas partes (art. 14.º). Na falta de escolha de lei, a norma de conflitos subsidiária especial (art. 5.º) manda aplicar a lei da Estado da residência habitual comum do lesado e agente[fn:24]; na falta de residência habitual comum, determina-se a lei reguladora da responsabilidade decorrente de produtos recorrendo a três conexões cumulativas sucessivas ou subsidiárias, sujeitas a uma cláusula de previsibilidade. Será assim aplicável a lei do Estado da residência habitual do lesado, da aquisição do produto ou da ocorrência do dano, desde que seja /simultaneamente/ a lei do Estado da comercialização do produto /e/ fosse razoavelmente previsível ao agente a comercialização do produto, ou de um produto do mesmo tipo, nesse Estado. Nos casos em que a opere a cláusula de previsibilidade e nos casos em que produto não seja comercializado nos Estados da residência habitual do lesado, da aquisição do produto e da ocorrência do dano, será aplicável a lei do Estado da residência habitual do agente[fn:25]. Por fim, todas as conexões, com exceção da escolha de lei pelas partes, estão sujeitas a uma cláusula de exceção.

A solução conflitual, sumariamente descrita, consagra sete conexões diferentes, a saber: /(i)/ lei do Estado escolhida pelas partes; /(ii)/ lei do Estado da residência habitual comum de lesado e agente; /(iii)/ lei do Estado da residência habitual do lesado e da comercialização do produto; /(iv)/ lei do Estado da aquisição e comercialização do produto; /(v)/ lei do Estado do dano e da comercialização do produto; /(vi)/ lei do Estado da residência habitual do agente; e /(vii)/ lei do Estado que, no caso concreto, tenha uma conexão manifestamente mais estreita com a situação do que os Estados designados em /(ii)/ a /(vi)/.

Assinala-se que esta solução tem muito em comum com a consagrada para as obrigações extracontratuais em geral: a conexão primária é a mesma (art. 14.º) e o artigo 5.º só substitui a /lex damni/, consagrada no artigo 4.º, n.º 1, do Regulamento Roma II, uma vez que mantém o elemento de conexão residência habitual comum e a cláusula de exceção. A especificidade na determinação da lei aplicável à responsabilidade decorrente de produtos é a substituição da /lex damni/ por 3 conexões cumulativas sucessivas ou subsidiárias, sujeitas a uma cláusula de previsibilidade[fn:26].

Antes de analisarmos concretamente cada uma das conexões consagradas nesta solução conflitual, cabe debruçarmo-nos sobre algumas questões de carácter mais geral. A primeira destas questões é relativa a natureza da obrigação do produtor. Esta solução conflitual, mercê do âmbito de aplicação em razão da matéria do Regulamento Roma II[fn:27], só é aplicável à responsabilidade /extracontratual/ do produtor. Eventuais pedidos indemnizatórios fundados em responsabilidade /contratual/ do produtor, no contexto de uma situação transnacional, são regulados pela lei designada aplicável nos termos do Regulamento Roma I[fn:28]. O conceito de obrigação extracontratual do Regulamento Roma II deve ser objeto de interpretação autónoma[fn:29] relativamente ao Direito dos Estados-Membros, de maneira a assegurar a harmonia jurídica internacional e a segurança jurídica. Em especial, o Tribunal de Justiça tem vincado que a interpretação dos atos comunitários deve ter em conta o contexto da disposição e o objetivo prosseguido pela regulamentação em causa[Cf., por exemplo, Acórdão do TJ de 27 de setembro de 1988, /Kalfelis/, C-189/97, EU:C:1988:459, considerandos n.ºs 15 e 16, Acórdão do TJ de 17 de dezembro de 2002, /Tacconi/, C-334/00, EU:C:2002:499, considerando n.º 19, Acórdão do TJ de 20 de janeiro de 2005, /Engler/, C-27/02, EU:C:2005:33, considerandos n.ºs 33 e 50, e Acórdão do TJ de 2 de abril de 2009, /A/, C-523/07, EU:C:2009:225, considerando n.º 34. Na doutrina portuguesa, cf., em geral, @pinheiro2014, pp. 460-461; @pinheiro2015, p. 472; @pinheiro2019c, pp. 49-50 e 129; e, em sede do Regulamento Roma II, @oliveira2011, pp. 213 e ss.]. O Regulamento Roma II não define o conceito de obrigação extracontratual[Sobre a definição deste conceito no Regulamento Roma II, cf. @pinheiro2015, pp. 472 e ss.; @oliveira2011, pp. 220 e ss.; @illmer2011, pp. 36 e ss.; @calliess2015, pp. 472 e ss.; e  @magnus2019, pp. 70 e ess.]. É possível, no entanto e atendendo ao considerando n.º 7 do Regulamento Roma II, recorrer à jurisprudência do TJ proferida sobre este conceito no âmbito da Convenção de Bruxelas[fn:30] e dos Regulamentos Bruxelas I[fn:31] e Bruxelas I /bis/[fn:32]. Decorre desta jurisprudência que o conceito de obrigação extracontratual é um conceito negativo: inclui as obrigações que não podem ser consideradas como obrigações contratuais[fn:33]. O conceito de obrigação contratual tem vindo a ser definido pelo TJ como um compromisso livremente assumido por uma parte perante outra[fn:34]. Nos casos de responsabilidade do produtor, em que este seja demandado por um utilizador do produto que o adquiriu a terceiro, a inexistência de uma relação contratual entre eles parece suficiente para concluir que estaremos perante uma obrigação extracontratual[fn:35].

O Regulamento Roma II define o conceito de dano, no artigo 2.º, como abrangendo "todas as consequências decorrentes da responsabilidade fundada em acto lícito, ilícito ou no risco, do enriquecimento sem causa, da /negotiorum gestio/ ou da /culpa in contrahendo/." Este conceito de dano é mais amplo do que o previsto no artigo 9.º da Diretiva em matéria de responsabilidade decorrente de produtos defeituosos[fn:36]. Pode assim suscitar-se a questão de saber se o conceito de dano da norma de conflitos especial do artigo 5.º deve entender-se em conformidade com o previsto na Diretiva ou no artigo 2.º do Regulamento Roma II. A melhor solução é esta última. Embora haja uma proximidade entre a norma de conflitos especial do artigo 5.º e a Diretiva em matéria de responsabilidade decorrente de produtos defeituosos, releva-se que esta Diretiva não harmoniza completamente a matéria da responsabilidade por produtos defeituosos[fn:37] e que as normas de conflitos do Regulamento Roma II tem carácter universal, isto é, o artigo 5.º pode designar como aplicável a lei de um Estado terceiro, que não está sujeito à obrigação de transposição da Diretiva para o seu Direito nacional. Deste modo, a maior amplitude do artigo 5.º e a interpretação declarativa do artigo 2.º apontam no sentido de que o conceito de dano a adotar é o do artigo 2.º do Regulamento Roma II[Cf., neste sentido, @palaomoreno2010, p. 55; @whittaker2011, p. 460; @calliess2015, p. 540; @magnus2019, p. 222; contra @stone2009, pp. 181-182; e @risso2019, p. 216.].

A redação da norma de conflitos especial na Proposta e na Proposta alterada da Comissão Europeia era clara no sentido de que esta se aplicava em matéria de responsabilidade causada por um produto defeituoso[fn:38]. Todavia, a redação final do artigo 5.º do Regulamento Roma II, que resultou da Posição Comum do Conselho, eliminou do texto do preceito a expressão "produto defeituoso", referindo-se apenas a "produto". A menção a produtos defeituosos subsiste unicamente na epígrafe do artigo e apenas nas versões portuguesa e espanhola[fn:39]. Pode assim suscitar-se a questão se, com esta alteração, se pretendeu alargar o âmbito de aplicação material desta norma de conflitos, de modo a abranger /também/ os danos causados por produtos, mesmo que esses danos não tenham sido causados por um defeito do produto[A questão é discutida, por exemplo, na Áustria, como se refere em  @britishinstituteofinternationalandcomparativelawbiicl2021, p. 105.]. Embora seja questão que não é de particular importância para o objeto deste estudo, uma vez que não se discute a inclusão no âmbito de aplicação deste preceito da responsabilidade do produtor por danos causados por produtos defeituosos, entendemos que esta alteração da redação do preceito não visou alargar o seu âmbito. Nada nos elementos preparatórios permite fundar o entendimento de que o Conselho, com a sua Posição Comum, pretendeu alargar o âmbito de aplicação material da regra inicialmente proposta pela Comissão, por exemplo, aos danos causados por produtos perigosos, e uma interpretação teleológica do preceito, atendendo às suas conexões e à proximidade da solução conflitual adotada com a da Convenção da Haia, aponta no sentido de a norma de conflitos especial designar apenas a lei aplicável à responsabilidade extracontratual decorrente de produtos defeituosos[Cf., neste sentido, @kozyris2008, pp. 487-488; @illmer2009, p. 283; @illmer2011, pp. 122-123; @stone2009, pp. 180-181; @pinheiro2015, p. 488; e, aparentemente, @ramos2016e, p. 118; considerando que o âmbito de aplicação material do artigo 5.º não é claro, cf. @franzina2008, p. 1004, nota de rodapé n.º 141; contra, cf. @calliess2015, pp. 542-543; e @magnus2019, pp. 217-218.].

O conceito de produto, determinante no artigo 5.º do Regulamento Roma II, também não é definido. Atendendo a que, como defendemos /supra/, o preceito determina apenas a lei aplicável à responsabilidade extracontratual decorrente de danos causados por produtos defeituosos, o conceito de produto deve interpretar-se em conformidade com a definição dada pelo artigo 2.º da Diretiva sobre responsabilidade decorrente de produtos defeituosos. Assim, deve entender-se por produto qualquer bem móvel, mesmo se incorporado noutro bem móvel ou imóvel, incluindo a eletricidade[Esta solução foi defendida pela Comissão Europeia na exposição de motivos da sua Proposta, p. 14, e é igualmente a posição maioritária na doutrina. Cf., neste sentido, @stone2009, p. 181; @illmer2009, p. 283; @palaomoreno2010, pp. 55-56; @illmer2011, p. 122; @whittaker2011, p. 457; @pinheiro2015, p. 489; @calliess2015, pp. 540-541; contra  @magnus2019, pp. 216-217, nas quais refere que o conceito de produto do artigo 5.º do Regulamento Roma II abrange todos os produtos enquadráveis na definição do artigo 2.º da Diretiva /e/ também aqueles que sejam apenas enquadráveis nas normas de Direito material interno; esta última ideia parece dificilmente compaginável com a ideia de interpretação autónoma do conceito de produto].

* Conexão primária: autonomia privada

A conexão primária é a escolha de lei pelas partes. O Regulamento Roma II estabelece a escolha de lei pelas partes como principal conexão para a generalidade da responsabilidade extracontratual, com exceção das obrigações extracontratuais decorrentes de um ato concorrência desleal ou da violação de um direito de propriedade intelectual[fn:40]. Visa-se, com esta conexão primária, "respeitar o princípio da autonomia das partes e reforçar a certeza jurídica"[fn:41].

A consagração da autonomia privada, em sede de responsabilidade extrcontratual do produtor, não suscita reparos. Estamos no âmbito de direitos patrimoniais disponíveis. A possibilidade de as partes escolherem a lei aplicável traduz, a nível conflitual, a liberdade de composição das situações jurídicas de que dispõem as partes a nível de Direito material. Concorda-se, igualmente, que a lei escolhida pelas partes reforça a certeza jurídica. Atendendo ao elevado número de conexões que compõem a solução conflitual em matéria de responsabilidade extracontratual do produtor, ao facto de algumas delas estarem condicionadas a uma cláusula de previsibilidade e de todas, com exceção da escolha de lei, estarem sujeitas a uma cláusula de exceção, parece-nos inequívoco que a escolha da lei permite determinar, de modo mais certo e seguro, qual a lei aplicável.

O artigo 14.º do Regulamento Roma II não introduz muitos limites à /professio iuris/ e os que introduz são, na sua maioria, semelhantes aos que existem na consagração da /professio iuris/ no Regulamento Roma I que determina a lei reguladora das obrigações contratuais. Assim, as partes só podem escolher a lei de um Estado. Quando a situação subjacente esteja exclusivamente ligada com Estados-Membros da União Europeia, a escolha de uma lei de um Estado terceiro (Estado que não é membro da União Europeia) não afasta as dispoições imperativas de direito da União Europeia[fn:42]. No caso da responsabilidade extracontratual do produtor a escolha, nestes casos, da lei de um Estado terceiro não permite afastar a aplicação das disposições imperativas que resultam da transposição da Diretiva sobre produtos no Estado-Membro do foro[Cf., neste sentido, @calliess2015, pp. 720-721.]. De igual modo, sempre que todos os elementos relevantes da situação se situem, no momento em que ocorre o facto que dá origem ao dano, num país que não seja o país da lei escolhida, a escolha das partes não prejudica a aplicação das disposições da lei desse país (que não é o país da lei escolhida pelas partes) não derrogáveis por acordo. Sobretudo no âmbito do lugar paralelo do artigo 3.º, n.º 3, do Regulamento Roma I, é controversa a interpretação deste preceito: alguns autores advogam que o preceito visa impedir que as partes, através do recurso à /professio iuris/, consigam escolher uma lei aplicável a uma situação que era, antes da escolha, puramente interna **XX colocar DMV e Giuliani / Lagarde**; outros advogam que se a situação subjacente era puramente interna, a escolha de lei pelas partes não tem a capacidade de a transformar numa situação privada internacional e que, por isso, o artigo 3.º, n.º 3, do Regulamento Roma I não visa essas situações, uma vez que o âmbito de aplicação espacial do Regulamento não se encontra preenchido. Sustentam, por isso, que o preceito é aplicável apenas nos casos em que estejamos perante uma situação relativamente internacional: a situação subjacente está unicamente ligada com um determinado Estado, que não é o da lei escolhida pelas partes e o litígio coloca-se perante os tribunais de um Estado-Membro vinculado ao Regulamento Roma I (que não é o Estado com que a situação subjacente está ligada) **XX colocar referência à tese do LLP**.

Uma das principais diferenças na consagração da /professio iuris/ no Regulamento Roma II diz respeito ao momento em que a escolha pode ser efetuada: em regra, a escolha de lei só pode ser efetuda pelas partes por acordo /posterior ao facto que dê origem ao dano/[fn:43]. Pensa-se que são, no essencial, duas as razões que presidem a esta limitação temporal. A primeira diz respeito à indeterminabilidade dos sujeitos. Em momento anterior ao facto que dá origem ao dano, em regra não é possível determinar quem será o agente e quem será o lesado. Muitas obrigações extracontratuais surgem sem que haja uma relação pré-existente entre lesado e agente. Assim, em muitos casos não será possível escolher previamente a lei aplicável, por não ser possível determinar com quem celebrar o acordo de escolha de lei. Esta limitação temporal visa também a proteção da parte mais fraca[fn:44]. Desde logo, porque apenas as partes que "desenvolvam actividades económicas" podem celebrar um acordo de escolha de lei em momento /anterior/ ao facto que dê origem ao dano[fn:45]. Exclui-se, assim, a possibilidade de escolher a lei reguladora das obrigações extracontratuais em momento anterior ao facto gerador do dano nas relações entre consumidores (/C2C/) e entre profissionais e consumidores (/B2C/).

Em matéria de responsabilidade extracontratual do produtor, em regra, não existirá uma relação pré-existente entre agente (produtor) e lesado, o que significa que o recurso à /professio iuris/ será limitado. Nos casos em que exista uma relação pré-existente, salienta-se que o acordo de escolha de lei só poderá ser celebrado em momento anterior ao facto gerador do dano se todas as partes envolvidas na sua celebração exercerem atividades profissionais[Cf., neste sentido, @magnus2019, pp. 496-497.]. Tal significa que também o lesado terá de exercer atividade profissional. A isto acresce que o acordo de escolha de lei terá de ser celebrado "mediante convenção livremente negociada", o que parece vedar acordos de escolha de lei baseados na adesão a formulários[Cf., neste sentido, @pinheiro2015, p. 477; e @calliess2015, pp. 713-714; @magnus2019, pp. 501-503, defende que a utilização de formulários constitui presunção /ilidível/ de que a convenção /não/ foi livremente negociada; contra, cf. @illmer2011, pp. 336-337, que parece entender que a regra constante do formulário de uma parte pode ter sido /livremente/ aceite pela outra, não exigindo, por isso, que tenha havido uma liberdade de estipulação.].

O acordo de escolha de lei só pode ser celebrado em momento posterior ao facto que dê origem ao dano quando uma das parte não exerça atividades profissionais. Crê-se, porém, que esta limitação não é, em matéria de responsabilidade extracontratual do produtor, particularmente adequada para proteger a parte (presumivelmente) mais vulnerável, aquela que não exerce atividades profissionais. Isto porque, nos casos de responsabilidade por produtos defeituosos, muitas vezes haverá uma dilação temporal entre a prática do facto - que será, em regra e consoante o defeito, o desenho, produção ou colocação no comércio do produto[@fawcett1993, p. 211.] - e a ocorrência do dano, que ocorrerá, em regra, apenas em momento posterior à aquisição do produto por uma pessoa, que poderá ou não ser o lesado. Atente-se que, durante a dilação entre a prática do facto e a ocorrência do dano, é possível celebrar um acordo de escolha de lei nos termos do artigo 14.º, n.º 1, alínea /a)/ do Regulamento Roma II, pois estamos em /momento posterior/ à prático do facto. No entanto, como estamos ainda antes da ocorrência do dano, isto é, como o lesado ainda não sofreu qualquer lesão na sua esfera jurídica, é possível que ele não tenha ainda uma correta perceção da importância que reveste um (eventual) acordo de escolha de lei nesta matéria.

Apesar desta reserva, considera-se que a /professio iuris/ será pouco utilizada - o que se tem vindo a verificar na prática - sobretudo pela dificuldade em determinar quem serão os sujeitos, na falta de uma relação pré-existente.

* Conexão subsidiária especial
** Residência habitual comum (art. 4.º/2)

Na falta de escolha de lei, é aplicável a lei do Estado da residência habitual comum de agente e lesado (/lex domicillii communis/)[fn:46]. Esta norma de conflitos é muitas vezes entendida como inspirada[Cf., por exemplo, @pinheiro2015, p. 484.] na jurisprudência norte-americana /Babcock v. Jackson/[fn:47], em que o tribunal afastou a aplicação da /lex loci delicti commissi/ em favor da lei da residência habitual comum do agente e lesado, por considerar que a primeira tinha carácter fortuito e a segunda uma ligação mais significativa com o litígio. Assinala-se que, aquando da elaboração do Regulamento Roma II, alguns Estados-Membros consagravam no seu Direito Internacional Privado de fonte interna desvios semelhantes assentes na lei do Estado da residência habitual comum, na lei do Estado da nacionalidade comum ou na lei do Estado da residência habitual ou da nacionalidade comum[fn:48].

A aplicação da lei do Estado da residência habitual de agente e lesado parece justificar-se em face da conexão especial que existe por via de estes estarem integrados na mesma comunidade jurídica[fn:49]. A aplicação da /lex domicilli communis/ pode também justificar-se por permitir uma redução dos custos de litigância e uma coincidência entre /forum/ e /ius/: residindo agente e lesado habitualmente no mesmo Estado, é provável que o litígio seja intentado no Estado em que ambos residam (e não no Estado em que foi praticado o facto lesivo ou ocorreu o dano) por ser nesse Estado que agente e lesado têm maior facilidade no acesso ao Direito. Nesses casos, a aplicação da /lex domicilli communis/ permite a aplicação que tribunal do foro aplique o seu próprio Direito material. Pode também, em muitos (mas não em todos os) casos, corresponder à legítima expetativa das partes[fn:50].

O conceito de residência habitual encontra-se apenas /parcialmente/ definido no artigo 23.º do Regulamento Roma II. Este preceito define que a residência habitual das pessoas coletivas e outra entidades sem personalidade jurídica é, em regra, o local onde se situa a respetiva administração central. Nos casos em que o facto que dá origem ao dano, ou o dano ocorra, no exercício da actividade de uma sucursal, agência ou outro estabelecimento, considera-se que a residência habitual corresponde ao local onde se situa a sucursal, agência ou outro estabelecimento. Estabelece igualmente que a residência habitual das pessoas singulares que atuam no exercício de uma atividade profissional se situa no local do seu estabelecimento principal.

Porém, não se encontra definido o conceito de residência habitual das pessoas singulares que não atuam no exercício de uma atividade profissional. Este conceito deve, não obstante, ser interpretado autonomamente. Entende-se que é possível obter orientações para a definição deste conceito na jurisprudência do Tribunal de Justiça da União Europeia que se debruçou sobre o conceito no âmbito de outros instrumentos de Direito Internacional Privado da União Europeia, nomeadamente o Regulamento Bruxelas II /bis/[fn:51]. O conceito tem sido mais desenvolvido na jurisprudência do Tribunal de Justiça da União Euopeia no contexto da residência habitual do menor.

Muito recentemente, o Tribunal de Justiça da União Europeia proferiu acórdão  no qual se debruça sobre o conceito de residência habitual dos cônjuges[fn:52]. Socorrendo-se da sua jurisprudência em matéria de residência habitual de menores, o Tribunal de Justiça reitera que a noção de residência habitual é essencialmente uma questão de facto, que se determina mediante a análise do conjunto de todas as circunstâncias do caso concreto[fn:53]. A residência habitual corresponde, por isso, ao local onde se situa o centro de vida do interessado e é, em princípio, caracterizada por dois elementos: a vontade do interessado fixar o seu centro de vida num determinado local e a duração, condições e regularidade da sua presença nesse determinado local, que deve dar nota de uma relação estreita e estável entre o interessado e esse local[fn:54]. Neste acórdão, o Tribunal de Justiça considerou que uma pessoa singular (o cônjuge) só pode ter, num determinado momento, uma residência habitual[fn:55].

A residência habitual comum deve existir no momento em que ocorre o dano. Assinala-se que, nos casos de responsabilidade extracontratual por danos decorrentes de produtos defeituosos, a lei do Estado da residência habitual comum de agente e lesado é aplicável /mesmo/ que o produto, ou um produto do mesmo tipo, não tenha sido comercializado nesse Estado /ou/ que não fosse razoavelmente previsível ao agente a sua comercialização nesse Estado. Esta conclusão decorre da letra do preceito e da teleologia da conexão: o que parece fundar a aplicação da /lex domicilli communis/ é, essencialmente, a especial ligação decorrente dos sujeitos estarem integrados numa mesma comunidade jurídica. O que não significa que estes elementos não possam ter uma relevância indireta, por via da cláusula de exceção consagrada no artigo 5.º, n.º 2, do Regulamento Roma II[Cf., neste sentido, @calliess2015, pp. 548-549; e @magnus2019, p. 225.].

** Conexões cumulativas sucessivas ou subsidárias

Não tendo agente e lesado resdiência habitual comum, a lei reguladora é determinada por três conexões cumulativas sucessivas ou subsidiárias, a saber, a lei do Estado da residência habitual do lesado, da aquisição do produto ou da ocorrência do dano, desde que cada uma destas seja /simultaneamente/ a lei do Estado da comercialização do produto /e/ fosse razoavelmente previsível ao agente a comercialização do produto, ou de um produto do mesmo tipo, em cada um desses Estados.

As três conexões cumulativas sucessivas ou subsidiárias estabelecem três elementos de conexão distintos (residência habitual do lesado, lugar da aquisição do produto e lugar onde ocorre o dano) e um elemento de conexão comum (lugar da comercialização).

A especifidade do elemento de conexão residência habitual do lesado consiste na interpretação autónoma do conceito de residência habitual, que só é parcialmente definido no artigo 23.º do Regulamento Roma II. Remete-se para o que se escreveu /supra/ aquando da análise da /lex domicilli communis/.

O elemento de conexão lugar da aquisição do produto refere-se, claramente, ao /concreto/ produto cujo defeito deu origem a um dano. O termo aquisição deve ser interpretado de modo a abranger aquisições onerosas ou gratuitas. Mais dúvidas suscita a questão de saber se releva apenas o lugar da primeira aquisição do produto ou se releva igualmente o lugar de aquisições subsequentes do mesmo produto. A letra do preceito depõe neste último sentido, ao não qualificar a aquisição, o que permite entender que relevam as aquisições originárias ou subsequentes. Por outro lado, a procura de um justo equilíbrio entre os interesses do agente e lesado parece depor contra a relevância do lugar das aquisições subsequentes, pois estas não serão cognoscíveis para o agente (produtor). Dir-se-á, no entanto, que esta questão é, pelo menos, mitigada pela cláusula de previsibilidade: se a aquisição derivada ocorrer em Estado diferente do da aquisição originária, o agente pode invocar que não lhe era razoavelmente previsível a comercialização daquele produto naquele país, salvo se, através da sua rede comercial, também disponibilizou nesse país produtos do mesmo tipo. Pensa-se, por isso, que a interpretação mais lata é a melhor[Cf., neste sentido, @illmer2009, p. 287.].

Outra questão associada a este elemento de conexão é a de saber se ele é aplicável a todos as tipologias de lesados. Este elemento de conexão é aplicável quando a pessoa que adquiriu o produto é também a pessoa que sofreu o dano. Parece igualmente aplicável quando o lesado, não sendo o adquirente do produto, é uma pessoa que utiliza o produto, em regra, conjuntamente com o adquirente, /v.g./ familiares ou pessoas que vivem em economia comum com o adquirente[Cf., neste sentido, @magnus2019, p. 227.]. A aplicação da lei do lugar da aquisição do produto (mesmo que essa lei seja igualmente a lei do Estado onde o produto foi comercializado) não parece adequada quando o lesado é um terceiro que não tem qualquer relação com o adquirente (/bystander/)[Cf., neste sentido,  @illmer2009, p. 287; e  @magnus2019, p. 227.]. Nestes casos, parece que se deverá recorrer à cláusula de exceção.

O elemento de conexão lugar onde ocorre o dano corresponde, e por isso deve ser interpretado da mesma forma, à /lex damni/ consagrada no artigo 4.º, n.º 1, do Regulamento Roma II. Como resulta expressamente deste último artigo, não releva nem o lugar da prática do facto (/lex loci delicti comissi/) nem o lugar onde ocorram as consequências indiretas desse facto. Esta solução é justificada por o lugar da prática do facto ser, muitas vezes, imprevisível e de pouca e nenhuma importância para o lesado e, em contraponto, o lugar das consequências indiretas ser, muitas vezes, igualmente imprevisível, mas para o agente. A procura de um justo equilíbrio entre os interesses de agente e lesado parece apontar assim para a lei do lugar onde ocorre o dano direto[fn:56]. E "(...) o país onde os danos ocorrem deverá ser o país em que o dano tenha sido infligido, respetivamente, à pessoa ou ao património"[fn:57]. Nesta ótica, o dano direto tem de corresponder à ofensa de um direito ou interesse legalmente protegidas e às consequências imediatas dessa ofensa na pessoa ou património do lesado[Cf., neste sentido, @pinheiro2015, pp. 483-484; @calliess2015, pp. 503-504; @ramos2016e, pp. 115-116; @magnus2019, pp. 164 e ss.; @vicente2020, p. 201.].

O elemento de conexão /comum/ é o lugar da comercialização do produto. O conceito de comercialização não é definido no Regulamento Roma II. Não obstante, carece de uma interpretação autónoma.

Poder-se-ia equacionar uma equiparação com o conceito de "colocação em circulação" da Diretiva sobre responsabilidade decorrente de produtos defeituosos, já interpretado pelo Tribunal de Justiça "(...) no sentido de que um produto é colocado em circulação quando sai do processo de fabrico realizado pelo produtor e entra num processo de comercialização em que se encontra no estado de oferta ao público com vista a ser utilizado ou consumido."[fn:58] Esta ideia, porém, não parece a melhor[@illmer2009, p. XXX; @illmer2011, p. 131; @calliess2015, p. 549; e @magnus2019, p. 221.]. O conceito de colocação em circulação surge, na Diretiva, com o intuito de precisar um determinado momento (artigos 6.º, n.º 1, al. /a)/, 6.º, n.º 2, e 11.º) ou como meio de defesa do produtor (artigo 7.º, als. /a)/ e /e)/). No Regulamento Roma II, o conceito parece mais ligado à possiblidade de um utilizador final do produto poder adquirí-lo, independentemente de quem o coloca em circulação nesse país. Considera-se, por isso, que se deve entender que há comercialização num dado país quando se verifica a disponibilização do produto (presencialmente ou à distância, /v.g./, através da /Internet/) aos utilizadores finais que aí residem[Cf., neste sentido, @illmer2009, pp. 290-292; @illmer2011, p. 130; em sentido semelhante, @calliess2015, pp. 550-551, defendendo que o conceito assenta em dois elementos: (i) a comercialização lícita (ii) através de meios comerciais, nomeadamente uma rede de distribuição; @hartley2008, p. 904, considera que o conceito exige a organização de uma rede para vendas em massa de um produto estandardizado; em sentido aparentemente mais amplo @magnus2019, p. 220, ao entender que o conceito de comercialização pode encontrar-se, em certos casos, preenchido mesmo quando se dirigem mensagens publicitárias a utilizadores finais do produto num dado país, mas não se dá uma verdadeira oportunidade de esses utilizadores finais adquirirem o produto.].

Suscita igualmente dúvidas o que é que tem de ser efetivamente comercializado: o /concreto/ produto defeituoso que causou o dano /ou/ é suficiente que seja comercializado um produto /do mesmo tipo/? A questão surge, desde logo, porque nas alíneas do artigo 5.º, n.º 1, do Regulamento Roma II se utiliza a expressão "se /o produto/ tiver sido comercializado nesse país" enquanto na cláusula de previsibilidade se utiliza a expressão "essa pessoa não puder razoavelmente prever a comercialização /do produto, ou de um produto do mesmo tipo/, no país cuja lei é aplicável, ao abrigo das alíneas a), b) ou c)."[fn:59] A letra do preceito parece, por isso, apontar que a comercialização se refere ao /concreto/ produto defeituoso que causou o dano[Aparentemente neste sentido, embora criticando a solução, cf. @hartley2008, p. 904.]. Parece-nos, porém, que essa interpretação não é a melhor. Se a comercialização se referir apenas ao concreto produto defeituoso que causou o dano, na maioria das situações este elemento de conexão será coincidente com o elemento de conexão lugar de aquisição do produto[fn:60]. E, como a comercialização é o elemento de conexão /comum/, esta interpretação acarreta uma (muito) significativa compressão do espaço e relevância de aplicação dos outros elementos de conexão consagrados pelo legislador (residência habitual do lesado e lugar onde ocorreu o dano). Dito de outra forma, essa (muito) significativa compressão afetaria de tal forma a ponderação de interesses de agente e lesado e procura de um justo equilíbrio entre eles, que seria preferível consagrar apenas uma conexão singular simples, assente no lugar da aquisição do produto e flexibilizada mediante uma cláusula de exceção. Entende-se, por isso, que o elemento de conexão /comum/ se preenche quando houve comercialização /ou/ do concreto produto defeituoso que causou o dano /ou/ de um produto do mesmo tipo[Cf., neste sentido, @illmer2009, pp. 292-293; @illmer2011, pp. 132-133; e @magnus2019, pp. 220-221; contra, ver @hartley2008, p. 904; e @stone2009, p. 188; e @calliess2015, pp. 552-553.].

A posição sustentada acarreta uma nova questão: o que se deve entender por um produto do mesmo tipo? Em primeiro lugar, parece-nos que terá de ser um produto comercializado pelo agente, ou pela sua rede de distribuição. Um produto, ainda que tenha características idênticas, comercializado por um outro (distinto e autónomo) operador económico não é suficiente para preencher o elemento de conexão do lugar da comercialização. Aponta neste sentido, pensa-se, a ideia de que se procura a aplicação de uma lei previsível, com que agente e lesado poderiam contar. Não é previsível que o agente veja aplicável uma determinada lei de um Estado (o da residência habitual do lesado ou o do lugar da ocorrência do dano) para o qual /não/ dirigiu a sua atividade económica, apenas porque um outro operador económico atua nessa mercado e comercializa produtos com as mesmas características de segurança. De entre os produtos comercializados pelo agente, são produtos do mesmo tipo aqueles que possuem idênticas características de segurança[Cf., neste sentido, @illmer2011, pp. 134-135; e @magnus2019, p. 220.].

Qualquer uma das três conexões cumulativas sucessivas ou subsidiárias está ainda condicionada por um cláusula de previsibilidade: o agente pode impedir a aplicação de qualquer uma destas três conexões cumulativas se provar que não podia razoavelmente prever a comercialização do produto, ou de um produto do mesmo tipo, nesses Estados.

Em primeiro lugar, e atendendo à conjugação da cláusula de previsibilidade com as alíneas do artigo 5.º, n.º 1, do Regulamento Roma II, entende-se que, caso a cláusula opera em relação a cada uma das conexões, mas não afeta a sua natureza sucessiva ou subsidiária. Assim, e por exemplo, caso o agente, numa determinada situação, consiga alegar e provar que não podia razoavelemente prever a comercialização do produto, ou de um produto do mesmo tipo, na lei do Estado da residência habitual do lesado, essa lei não será aplicável. Mas tal não significa, necessariamente, que será aplicável a lei do Estado da residência habitual do agente[fn:61]; primeiramente há que determinar o preenchimento das outras duas conexões cumulativas sucessivas ou subsidiárias e, em caso afirmativo, se também se verifica a claúsula de previsibilidade quanto a estas. Dito de outra forma: a  cláusula de previsibilidade só conduz à aplicação da lei do Estado da residência habitual do agente quando ela se verifica em relação às três conexões cumulativas sucessivas ou subsidiárias /ou/ quando se verifica em relação a alguma, mas as demais não operam porque não são, simultaneamente, o Estado da comercialização[Cf., neste sentido, @magnus2019, pp. 224-225; e, aparentemente, @calliess2015, p. 555.].

Pode igualmente suceder que o produto, ou um produto do mesmo tipo, não seja comercializado nem no Estado da residência habitual do lesado, nem no Estado da aquisição, nem no Estado onde ocorreu o dano. Neste caso, nenhuma das alíneas do artigo 5.º, n.º 1, do Regulamento Roma II se encontra preenchido e temos uma lacuna. Para integração desta lacuna foram essencialmente avançadas três soluções: /(i)/ aplicação da lei do Estado em que houve comercialização, que esteja mais próximo de um dos indicados nas alíneas /a)/ a /c)/ do n.º 1 do artigo 5.º[@britishinstituteofinternationalandcomparativelawbiicl2021, p. 34.]; /(ii)/ aplicação do artigo 4.º, norma de conflitos subsidiária geral[@hartley2008, pp. 904-905.]; e /(iii)/ aplicação analógica da lei do Estado da residência habitual do agente[Cf.  @illmer2009, pp. 296-297; @calliess2015, p. 561; @pinheiro2015, p. 489; e @magnus2019, pp. 228-229.].

A primeira proposta de solução não nos parece viável, porque redunda na aplicação de uma lei que é apenas a lei de um Estado onde foi comercializado um produto, ou um produto do mesmo tipo, o que colide com a intenção do legislador, que foi a de aplicar a lei de um Estado que reunia dois elementos de conexão. A aplicação do artigo 4.º também não parece a melhor solução, em face do carácter muitas vezes fortuito do elemento de conexão lugar do dano direto nos casos de responsabilidade extracontratual por danos decorrentes de produtos defeituosos. Recorda-se que a Comissão Europeia e o Conselho consideraram, aquando do processo legislativo, que a aplicação da /lex damni/ não permitia, nestes casos, prever a lei aplicável com uma certeza razoável, o que os levou a defender a criação e manutenção de uma norma de conflitos subsidiária especial. O que aponta no sentido de que se deve integrar a lacuna no seio e de acordo com o sistema delineado no próprio artigo 5.º do Regulamento Roma II. Por estes motivos, parece-nos que a melhor solução é a aplicação analógia da lei do Estado da residência habitual do agente. Releva-se que é esta a lei aplicável se o agente alegar e demonstrar que não podia razoavelemnte prever a comercialização do produto, ou de um produto do mesmo tipo, na lei do Estado da residência habitual do lesado, na lei do Estado da aquisição e na lei do Estado onde ocorreu o dano direto. Se o funcionamento da cláusula da previsibilidade - que também opera atendendo à comercialização - conduz, neste caso, a aplicação da lei do Estado da residência habitual do agente, então, por maioria de razão, deve aplicar-se essa mesma lei quando o produto, ou um produto do mesmo tipo, /não/ foi comercializado em nenhum desses três Estados.

** A cláusula de exceção (art. 5.º/2)

Por fim, consagra-se, no artigo 5.º, n.º 2, do Regulamento Roma II uma cláusula de exceção em termos essencialmente idênticos à prevista no artigo 4.º, n.º 3[fn:62]. Pode suscitar-se uma questão preliminar, em face da redação do artigo 5.º, n.º 1, e da remissão que nele consta para o artigo 4.º, n.º 2: está, ou não, a designação da lei do Estado da residência habitual comum de agente e lesado sujeita à cláusula de exceção. Apesar de o elemento literal não ser perfeitamente claro, pensa-se que a melhor solução, atendendo à teleologia do artigo 5.º e ao lugar paralelo do artigo 4.º é a de considerar que também a lei do Estado da residência habitual comum do agente e lesado está sujeita à cláusula de exceção.

Consideramos, por isso, que a claúsula de exceção só não condiciona a lei escolhida pelas partes.

A cláusula de exceção, assente no princípio da conexão mais estreita, visa flexibilizar as restantes normas de conflitos consagradas no (ou para onde remete o) artigo 5.º, que têm a natureza de normas de conflitos /rígidas/. Esta opção do legislador da União Europeia parece advir da prossecução de um objetivo geral: promover uma maior certeza e previsibilidade jurídicas[fn:63].

O artigo 5.º, n.º 2, utiliza a teoria da conexão acessória como exemplo de uma possível conexão manifestamente mais estreita. Possível, porque a conexão manifestamente mais estreita só pode analisar-se atendendo às circunstâncias do caso concreto. A sua verificação é, por isso, casuística. Devem evitar-se generalizações quanto à aplicação da cláusula de exceção a determinadas exceções, até porque se corre o risco de "cristalizar" a cláusula de exceção, reduzindo a margem de flexibilidade que ela poderia conceder às restantes normas de conflitos aplicáveis.

Feita esta ressalva, assinala-se que se exisitr um contrato prévio de aquisição (/v.g./ contrato de compra e venda) do produto entre produtor e lesado, a lei aplicável a este pode, num determinado caso concreto, consituir uma conexão manifestamente mais estreita que afasta as demais leis designadas nos termos das normas de conflitos do (ou para que remete o) artigo 5.º, n.º 1, do Regulamento Roma II[Este exemplo é dado pela maioria dos autores, sendo que @illmer2011, p. 139, parece mesmo considerar que nestes casos estaremos sempre perante uma conexão manifestamente mais estreita.]. Quando o lesado seja um terceiro que não adquiriu nem utilizou o produto, isto é, quando seja alguém que não tem qualquer relação com o utilizador final do produto, as conexões do artigo 5.º, n.º 1, do Regulamento Roma II podem não ser as mais adequadas. Para este lesado, a lei do Estado da comercialização não é particularmente significativa. Há, por isso, vários autores que advogam que, em certos casos concretos, será preferível acionar a cláusula de exceção e aplicar a /lex damni/[Cf., em sentido semelhante, @illmer2009, p. 302; @calliess2015, p. 563; e  @magnus2019, p. 230].

* Conclusão

Citar [@ramos2016e, p. 120], que considera o artigo 5.º "uma regra de conflitos particularmente complexa".

* Footnotes

[fn:63] Cf. considerandos 14, 18 e 20 do Regulamento Roma II.

[fn:62] A única diferença consiste na identificação da(s) norma(s) de conflitos na previsão. A cláusula de exceção do artigo 4.º, n.º 3, incide sobre os n.ºs 1 e 2 do mesmo preceito. A claúsula de exceção do artigo 5.º, n.º 2, incide sobre o n.º 1 desse preceito.

[fn:61] Artigo 5.º, n.º 1, 2.º parágrafo do Regulamento Roma II.

[fn:60] Não o será, por exemplo, nos casos em que haja uma aquisição subsequente num Estado diferente daquele em que ocorreu a aquisição originária.

[fn:59] Itálicos aditados.

[fn:58] Acórdão do TJ de 9 de fevereiro de 2006, /O'Byrne/, proc. C-127/04, EU:C:2006:93, cons. 32.

[fn:57] Considerando n.º 17 do Regulamento Roma II.

[fn:56] Cf. considerando n.º 16 do Regulamento Roma II.

[fn:55] Acórdão do TJ de 25 de novembro de 2021, /IB contra FA/, proc. C-289/20, EU:C:2021:955, cons. 62.

[fn:54] Acórdão do TJ de 25 de novembro de 2021, /IB contra FA/, proc. C-289/20, EU:C:2021:955, cons. 57.

[fn:53] Acórdão do TJ de 25 de novembro de 2021, /IB contra FA/, proc. C-289/20, EU:C:2021:955, cons. 52.

[fn:52] Acórdão do TJ de 25 de novembro de 2021, /IB contra FA/, proc. C-289/20, EU:C:2021:955.

[fn:51] Regulamento (CE) n.º 2201/2003 do Conselho, de 27 de Novembro de 2003, relativo à competência, ao reconhecimento e à execução de decisões em matéria matrimonial e em matéria de responsabilidade parental e que revoga o Regulamento (CE) n.º 1347/2000, publicado no JO L 338 de 23 de dezembro de 2003.

[fn:50] Cf. Proposta da Comissão Europeia, p. 12. Concorda-se, no entanto, que nem sempre a expetativa das partes será a aplicação da lei da residência habitual comum. Imagine-se, por exemplo, uma colisao de veículos entre duas pessoas com residência habitual em França que se encontram de férias em Portugal. Se as pessoas vieram de férias juntas, podem legitimamente esperar que se aplique ao seu litígio a lei da sua residência habitual; caso contrário, se não existir qualquer relação entre elas anterior à colisão, dificilmente terão a expetativa de aplicação da /lex domicilli communis/. O que não significa que não haja outras razões (as avançadas no texto) para se  aplicar essa lei.

[fn:49] Pode ler-se, no considerando n.º 18 do Regulamento Roma II, que "[...] O n.º 2 do artigo 4.º deverá ser visto como uma excepção a este princípio geral, criando uma conexão especial caso as partes tenham a sua residência habitual no mesmo país."

[fn:48] Cf., por exemplo, o artigo 99.º, §1º., n.º 1, do Código Civil belga; o artigo 62.º, n.º 2, da Lei de 31 de maio de 1995, n.º 218, que reforma o sistema italiano de Direito Internacional Privado; o artigo 40.º, n.º 2, da Lei de introdução ao Código Civil Alemão; e o artigo 45.º, n.º 3, do Código Civil português.

[fn:47] Babcock v. Jackson, 191 N.E.2d 279, 12 N.Y.2d 473 (N.Y. 1963).

[fn:46] Cf. artigo 4.º, n.º 2, aplicável por remissão da parte inicial do artigo 5.º, n.º 1, do Regulamento Roma II.

[fn:45] Cf. artigo 14.º, n.º 1, alínea /b)/ do Regulamento Roma II.

[fn:44] No considerando n.º 31 do Regulamento Roma II afirma-se que "É necessário proteger as partes mais vulneráveis, impondo determinadas condições a esta escolha."

[fn:43] Cf. artigo 14.º, n.º 1, alínea /a)/ do Regulamento Roma II. Confrontar o artigo 3.º, n.º 2, do Regulamento Roma I que permite a celebração do acordo de escolha de lei em qualquer momento.

[fn:42] Cf. artigo 14.º, n.º 3 do Regulamento Roma II. O conceito de Estado-Membro encontra-se definido no artigo 1.º, n.º 4, do Regulamento Roma II. /Vide/, também, o lugar paralelo do artigo 3.º, n.º 4, do Regulamento Roma I.

[fn:41] Cf. considerando n.º 31 do Regulamento Roma II.

[fn:40] Cf., respetivamente, artigos 6.º, n.º 4, 8.º, n.º 4, e 13.º do Regulamento Roma II.

[fn:39] A mesma distinção ocorre no considerando 20. As versões portuguesa e espanhola utilizam, respetivamente, "produtos defeituosos" e "productos defectuosos". As versões inglesa e francesa utilizam, respetivamente, "product liability" e "produits".

[fn:38] O artigo 4.º da Proposta e o artigo 6.º da Proposta alterada utilizam, no texto do preceito, nas versões portuguesa, inglesa e francesa, as expressões "produto defeituoso", "defective product" e "produit défectueux". As versões portuguesa e francesa utilizam ainda os respetivos termos na epígrafe dos artigos.

[fn:37] Cf. os artigos 9.º, 15.º e 16.º da Diretiva.

[fn:36] Directiva 85/374/CEE do Conselho, de 25 de Julho de 1985, relativa à aproximação das disposições legislativas, regulamentares e administrativas dos Estados-Membros em matéria de responsabilidade decorrente dos produtos defeituosos, publicada no JO L 210 de 7 de agosto de 1985, retificada por Retificação publicada no JO L 307 de 12 de novembro de 1988 e alterada pela Directiva 1999/34/CE do Parlamento Europeu e do Conselho, de 10 de Maio de 1999, que altera a Directiva 85/374/CEE do Conselho relativa à aproximação das disposições legislativas, regulamentares e administrativas dos Estados-Membros em matéria de responsabilidade decorrente dos produtos defeituosos, publicada no JO L 141 de 4 de junho de 1999 (doravante Diretiva ou Diretiva sobre responsabilidade decorrente de produtos defeituosos).

[fn:35] Neste sentido, Acórdão do TJ de 17 de junho de 1992, /Handte/, C-26/91, EU:C:1992:268, considerandos n.ºs 16 e 21.

[fn:34] Acórdão do TJ de 17 de junho de 1992, /Handte/, C-26/91, EU:C:1992:268, considerando n.º 15 e Acórdão do TJ de 20 de janeiro de 2005, /Engler/, C-27/02, EU:C:2005:33, considerandos n.ºs 50 e 51.

[fn:33] Acórdão do TJ de 27 de setembro de 1988, /Kalfelis/, C-189/97, EU:C:1988:459, considerando n.º 17.

[fn:32] Regulamento (UE) n.º 1215/2012 do Parlamento Europeu e do Conselho, de 12 de dezembro de 2012 , relativo à competência judiciária, ao reconhecimento e à execução de decisões em matéria civil e comercial (reformulação), publicado no JO L 351 de 20 de dezembro de 2012.

[fn:31] Regulamento (CE) n.º 44/2001 do Conselho, de 22 de Dezembro de 2000, relativo à competência judiciária, ao reconhecimento e à execução de decisões em matéria civil e comercial, publicado no JO L 12 de 16 de janeiro de 2001.

[fn:30] Convenção de Bruxelas de 1968 relativa à Competência Jurisdicional e à Execução de Decisões em matéria civil e comercial, versão consolidada, publicada no JO L 299 de 31 de dezembro de 1972.

[fn:29] Cf., neste sentido, o considerando n.º 11 do Regulamento Roma II.

[fn:28] Regulamento (CE) n.º 593/2008 do Parlamento Europeu e do Conselho, de 17 de Junho de 2008, sobre a lei aplicável às obrigações contratuais (Roma I), publicado no JO L 177 de 4 de julho de 2008.

[fn:27] Cf. artigo 1.º do Regulamento Roma II.

[fn:26] E, quando nenhuma destas conexões esteja preenchida ou se verifique a cláusula de previsibilidade, a aplicação da lei da residência habitual do agente.

[fn:25] Artigo 5.º, n.º 1, segundo parágrafo. A aplicação analógica deste preceito aos casos de não comercialização do produto será desenvolvida /infra/.

[fn:24] Artigo 4.º, n.º 2, aplicável por via da remissão constante do artigo 5.º, n.º 1, do Regulamento Roma II.

[fn:23] Cf., neste sentido, a exposição de motivos da Proposta da Comissão Europeia, p. 15 e a Posição Comum do Conselho, p. 79.

[fn:22] Cf. considerando 20.º do Regulamento Roma II. Negritos aditados.

[fn:21] Cf. Acórdão do Tribunal de Justiça (doravante TJ) de 17 de novembro de 2011, /Homawoo/, C-412/10, EU:C:2011:747, considerando 34.

[fn:20] Cf. considerando 16.º do Regulamento Roma II.

[fn:19] Cf. considerando 13.º do Regulamento Roma II.

[fn:18] Cf. considerandos 6.º e 14.º do Regulamento Roma II.

[fn:17] Doravante Convenção ou Convenção da Haia.

[fn:16] Comunicação da Comissão ao Parlamento Europeu em conformidade com o n.º 2, segundo parágrafo, do artigo 251.º do Tratado CE relativa à posição comum do Conselho respeitante à adopção de um regulamento do Parlamento Europeu e do Conselho sobre a lei aplicável às obrigações extracontratuais ("Roma II"), COM(2006) 566 final, p. 3 (doravante Comunicação).

[fn:15] /Idem/.

[fn:14] Cf. Posição Comum, nota justificativa do Conselho, p. 79.

[fn:13] Posição Comum (CE) N.º 22/2006, adoptada pelo Conselho em 25 de Setembro de 2006, tendo em vista a adopção do Regulamento (CE) n.º …/… do Parlamento Europeu e do Conselho, de …, relativo à lei aplicável às obrigações extracontratuais («ROMA II»), publicada no JO C 289E de 28 de novembro de 2006, pp. 68—83 (doravante Posição Comum).

(2006/C 289 E/04)
[fn:12] O artigo 6.º da Proposta alterada estabelecia: "Sem prejuízo do disposto nos nºs 2 e 3 do artigo +3º+ *_5º_*, a lei aplicável à obrigação extracontratual em caso de dano +ou risco de dano+ causado por um produto defeituoso é a lei do país em que a pessoa lesada tem a sua residência habitual, *_no momento da ocorrência do dano_*, salvo se a pessoa cuja responsabilidade é invocada provar que o produto foi comercializado neste país sem o seu consentimento, sendo então aplicável a lei do país em que a pessoa cuja responsabilidade é invocada tem a sua residência habitual." (destaques no original)

[fn:11] Cf. exposição de motivos da Proposta alterada, p. 6.

[fn:10] Cf. exposição de motivos da Proposta alterada, p. 4.

[fn:9] COM(2006) 83 final. Doravante Proposta alterada.

[fn:8] P6_TA(2005)0284.

[fn:7] O artigo 4.º da Proposta estabelecia: "Sem prejuízo do disposto nos nºs 2 e 3 do artigo 3º, a lei aplicável à obrigação extracontratual em caso de dano ou risco de dano causado por um produto defeituoso é a lei do país em que a pessoa lesada tem a sua residência habitual, salvo se a pessoa cuja responsabilidade é invocada provar que o produto foi comercializado neste país sem o seu consentimento, sendo então aplicável a lei do país em que a pessoa cuja responsabilidade é invocada tem a sua residência habitual."

[fn:6] Cf. exposição de motivos da Proposta, p. 15.

[fn:5] O concreto produto que causou o dano ou um produto do mesmo tipo. Isso decorre claramente da exposição de motivos da Proposta: "Quando a pessoa lesada adquire o produto num país diferente do da sua residência habitual, por exemplo, durante uma viagem, devem distinguir-se duas hipóteses: na primeira, adquiriu no estrangeiro um produto que é igualmente comercializado no país da sua residência, por exemplo, para beneficiar de uma promoção. Neste caso, o produtor já tinha previsto que a sua
actividade poderia ser avaliada ao abrigo das normas em vigor neste país e o artigo 4º designa a lei deste país cuja aplicação era previsível para as duas partes." (cf. p. 15).

[fn:4] COM(2003) 427 final. Doravante Proposta.

[fn:3] O Supremo Tribunal de Justiça caracterizou como ocasional "a estadia sem grande estabilidade e permanência, antes a título transitório e passageiro, ou seja, para durar por um período limitado, circunscrita à realização de um fim ou atividade pouco prolongada." (acórdão de 8 de novembro de 1979, /Boletim do Ministério da Justiça/, n.º 291, pp. 456 e ss.).

[fn:2] Regulamento (CE) n.º 864/2007 do Parlamento Europeu e do Conselho, de 11 de Julho de 2007, relativo à lei aplicável às obrigações extracontratuais (Roma II), publicado no Jornal Oficial (doravante JO) L 199, de 31 de julho de 2007.

[fn:1] A saber, Croácia, Eslóvenia, Espanha, Finlândia, França, Macedónia do Norte, Montenegro, Países Baixos e Sérvia.
